#FROM ubuntu:14.04
#MAINTAINER Matt Oliver <matt@oliver.com>
CMD ping localhost -t 5

#RUN apt-get update && apt-get install -y ruby ruby-dev apache2 icinga
#RUN gem install sinatra
#RUN touch /root/olver_is_awesome

#EXPOSE 80

#RUN service apache2 start




